INSERT INTO Major (major_id, school, name) VALUES
('BP343', 'TBS', 'Business'),
('BP214', 'SCD', 'Game Design'),
('BP312', 'TBS', 'Tourism and Hospitality Management'),
('BP222', 'SCD', 'Professional Communication'),
('BP070', 'SSET', 'Applied Science (Aviation)'),
('BH123', 'SSET', 'Robotics and Mechatronics Engineering'),
('BP351', 'TBS', 'Accounting'),
('BP309', 'SCD', 'Digital Media'),
('BP325', 'SCD', 'Digital Film and Video'),
('BP327', 'SCD', 'Fashion (Enterprise)'),
('BP162', 'SSET', 'Information Technology'),
('BH073', 'SSET', 'Electronic and Computer Systems Engineering'),
('BP318', 'TBS', 'Digital Marketing'),
('BP316', 'SCD', 'Design Studies'),
('BP317', 'SEUP', 'Languages'),
('BP154', 'SSET', 'Psychology'),
('BH120', 'SSET', 'Software Engineering'),
('BP199', 'SSET', 'Food Technology and Nutrition');


INSERT INTO Course (course_id, name) VALUES
('MKTG1205', 'Marketing Principles'),
('MKTG1419', 'Social Media and Mobile Marketing'),
('MKTG1420', 'Digital Business Development'),
('MKTG1422', 'Digital Marketing Communication'),
('OMGT2085', 'Intro to Logistics & Supply Chain Mgt'),
('OMGT2197', 'Procurement Mgmt and Global Sourcing'),
('ISYS2109', 'Business Information Systems'),
('MKTG1421', 'Consumer Psychology and Behaviour'),
('COSC2429', 'Introduction To Programming'),
('COSC2430', 'Web Programming'),
('COSC2440', 'Software Architecture: Design & Implementation'),
('COSC2652', 'User-centred Design'),
('ISYS3414', 'Practical Database Concepts'),
('COMM2596', 'Digital Narrative Theory and Practice'),
('COMM2752', 'Digital Media Specialisation 2'),
('COSC2532', 'Advanced Electronic Imaging'),
('VART3626', 'Photography 101'),
('VART3670', 'Creative Photography'),
('ECON1318', 'Economics for Tourism and Hospitality'),
('ACCT2105', 'Accounting in Organisations & Society'),
('ACCT2158', 'Financial Accounting and Analysis'),
('ACCT2160', 'Cost Analysis and Organisational Decisions'),
('BAFI3182', 'Financial Markets'),
('BAFI3184', 'Business Finance'),
('ECON1192', 'Macroeconomics 1'),
('ECON1193', 'Business Statistics 1'),
('ECON1194', 'Prices and Markets'),
('LAW2447', 'Commercial Law'),
('ACCT2197', 'Performance Analysis and Simulations'),
('EEET2482', 'Software Engineering Design'),
('EEET2599', 'Electrical Engineering 1'),
('EEET2600', 'Electronics'),
('EEET2601', 'Engineering Computing 1'),
('EEET2603', 'Introduction to Electrical and Electronic Engineering'),
('MATH2394', 'Engineering Mathematics'),
('OENG1181', 'Introduction to Professional Engineering Practice'),
('BAFI3239', 'Pattern Cutting for Production'),
('BUSM1784', 'Supply Chain Management'),
('MANU2492', 'Digital Applications for Fashion Enterprise 1'),
('MKTG1447', 'Introduction to Fashion Marketing'),
('VART3663', 'Computing for Fashion Design and Product Development'),
('VART3662', 'Introduction to Fashion Design'),
('LANG1306', 'Japanese 1'),
('LANG1307', 'Japanese 2'),
('LANG1321', 'Introduction to Language'),
('LANG1303', 'Ethics & Professional Issues in Translating & Interpreting'),
('LANG1308', 'Japanese 3'),
('LANG1310', 'Japanese 5'),
('LANG1318', 'Language and Society'),
('SOCU2252', 'Intercultural Communication'),
('SOCU2290', 'Working and Managing in Global Careers'),
('BUSM3299', 'The Entrepreneurial Process'),
('BUSM3310', 'Human Resource Management'),
('BUSM3311', 'International Business'),
('BUSM4092', 'Applied Entrepreneurship'),
('BUSM4186', 'Global Entrepreneurship'),
('BUSM4566', 'Tourism Planning & Resource Management'),
('BUSM4769', 'Employment Relations'),
('BUSM2301', 'Organisational Analysis'),
('BUSM2412', 'Marketing for Managers'),
('BUSM2479', 'Digital Entrepreneurship'),
('BUSM3244', 'Business and Economic Analysis'),
('BUSM3250', 'People and Organisations'),
('BUSM4037', 'Contemporary Issues in International Management'),
('BUSM4185', 'Introduction to Management'),
('BUSM4188', 'Leadership and Decision Making'),
('BUSM4488', 'Managing Across Cultures'),
('BUSM4561', 'Work in Global Society'),
('BUSM4568', 'Room Division Management'),
('BUSM4573', 'Business Communications and Professional Practice'),
('BUSM4621', 'Postgraduate Business Internship'),
('FOHO1024', 'International Food & Beverage Management'),
('INTE2562', 'Digital Innovation'),
('OMGT2272', 'International Logistics'),
('BUSM4553', 'Creativity, Innovation and Design'),
('BUSM4557', 'Contemporary Management: Issues and Challenges'),
('BUSM4489', 'Sustainable International Business Futures'),
('COMM2377', 'Modern Asia'),
('COMM2383', 'New Media, New Asia'),
('COMM2489', 'Asian Cinemas'),
('GRAP2659', 'Art Direction'),
('LANG1265', 'Vietnamese for Professional Communication'),
('COMM2497', 'Exploring Asian Popular Culture'),
('GRAP2413', 'Advertising Media');


INSERT INTO Category (category_id, name) VALUES
('CAT001', 'Mathematics'),
('CAT002', 'Physics'),
('CAT003', 'Chemistry'),
('CAT004', 'Biology'),
('CAT005', 'Engineering'),
('CAT006', 'Computer Science'),
('CAT007', 'Economics'),
('CAT008', 'Psychology'),
('CAT009', 'Literature'),
('CAT010', 'History'),
('CAT011', 'Philosophy'),
('CAT012', 'Political Science'),
('CAT013', 'Languages'),
('CAT014', 'Arts'),
('CAT015', 'Education'),
('CAT016', 'Business'),
('CAT017', 'Law'),
('CAT018', 'Medicine'),
('CAT019', 'Environmental Science'),
('CAT020', 'Sociology'),
('CAT001', 'Mathematics'),
('CAT002', 'Physics'),
('CAT003', 'Chemistry'),
('CAT004', 'Biology'),
('CAT005', 'Engineering'),
('CAT006', 'Computer Science'),
('CAT007', 'Economics'),
('CAT008', 'Psychology'),
('CAT009', 'Literature'),
('CAT010', 'History'),
('CAT011', 'Philosophy'),
('CAT012', 'Political Science'),
('CAT013', 'Languages'),
('CAT014', 'Arts'),
('CAT015', 'Education'),
('CAT016', 'Business'),
('CAT017', 'Law'),
('CAT018', 'Medicine'),
('CAT019', 'Environmental Science'),
('CAT020', 'Sociology');
