INSERT INTO Major (major_id, school, name) VALUES
('BP343', 'TBS', 'Business'),
('BP214', 'SCD', 'Game Design'),
('BP312', 'TBS', 'Tourism and Hospitality Management'),
('BP222', 'SCD', 'Professional Communication'),
('BP070', 'SSET', 'Applied Science (Aviation)'),
('BH123', 'SSET', 'Robotics and Mechatronics Engineering'),
('BP351', 'TBS', 'Accounting'),
('BP309', 'SCD', 'Digital Media'),
('BP325', 'SCD', 'Digital Film and Video'),
('BP327', 'SCD', 'Fashion (Enterprise)'),
('BP162', 'SSET', 'Information Technology'),
('BH073', 'SSET', 'Electronic and Computer Systems Engineering'),
('BP318', 'TBS', 'Digital Marketing'),
('BP316', 'SCD', 'Design Studies'),
('BP317', 'SEUP', 'Languages'),
('BP154', 'SSET', 'Psychology'),
('BH120', 'SSET', 'Software Engineering'),
('BP199', 'SSET', 'Food Technology and Nutrition');
